linkapp/urls.py
from django.urls import path
from .import views as v
urlpatterns = [
    path("",v.index,name="index"),
    path("reg",v.register,name="register"),
    path("login",v.loginn,name="login"),
    path("logout",v.logoutt,name="logout"),
    path("dashboard",v.dash,name="dashb"),
    path("details",v.details,name="details1"),
    path("deletes/<int:pk>",v.delete,name="delete1"),
    path("edit/<int:pk>",v.edits,name="edit1"),
    
]

linkedin/urls.py
from django.contrib import admin
from django.urls import path,include
from linkapp.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",index),
    path("linkedin-",include(("linkapp.urls","linkapp"),namespace="linkapps"))
]

linkapp/models.py
from django.db import models

from django.db import models
from datetime import datetime
from django import forms

class LoginForm(forms.Form):
    uname=forms.CharField(max_length=30,label="username")
    pswd=forms.CharField(max_length=30,label="password")

class Profile(models.Model):
    choice=(("Complete","complete"),
            ("Pending","pending"))
    title=models.CharField(max_length=300,default='')
    date=models.DateTimeField(auto_now=True)
    status=models.CharField(max_length=10,choices=choice,default=True)

    def __str__(self):
        return self.title


class ProfileForm(forms.ModelForm):
    class Meta:
        model=Profile
        fields="__all__"
    
        

linkapp/views.py
from django.shortcuts import render,redirect

# Create your views here.
from django.shortcuts import render,redirect
from django.contrib.auth.forms import UserCreationForm
from .models import *
from django.contrib.auth import login,logout,authenticate

from django.contrib.auth.models import User

def index(request):
    return render(request, "index.html")


def register(request):
    if request.method=="POST":
        obj=UserCreationForm(request.POST)
        obj.save()
        return redirect("/")
    else:
        d={"form":UserCreationForm}
        return render(request,'forms.html ',d)
    

def loginn(request):
    if request.method=='POST':
        uname=request.POST.get("uname")
        pswd=request.POST.get("pswd")
        user=authenticate(request,username=uname,password=pswd)
        if user is not None:
            request.session["id"]=user.id
            print(request.session.get("id"))
            login(request,user)
            return redirect("/linkedin-dashboard")
        else:
            d={'form':LoginForm}
            return render(request,'forms.html',d)

    else:
        d={'form':LoginForm}
        return render(request,'forms.html',d)
    
def dash(request):
       obj1=Profile.objects.all()
       if request.method=="POST":
        obj=ProfileForm(request.POST)
        obj.save()
        
        
        return redirect("/linkedin-dashboard")
       else:
        d={"form":ProfileForm,"data":obj1}
        return render(request,'dashboard.html ',d)
       
def details(request):
    obj=Profile.objects.all()
    d={"data":obj}
    return render(request,"sample.html",d)

def delete(request,pk):
    obj=Profile.objects.get(id=pk)
    obj.delete()
    return redirect("/linkedin-dashboard")

def edits(request,pk):
  data=Profile.objects.get(id=pk)
  if request.method=='POST':
    obj=ProfileForm(request.POST,instance=data)
    obj.save()
    return redirect("/linkedin-dashboard")
  else:
    d={'form':ProfileForm(instance=data)}
    return render(request,'dashboard.html',d)
    

def logoutt(request):
    logout(request)
    return redirect("/")    

linkapp/templates/dashboard.html
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
</head>

<body>
    
    <nav class="navbar navbar-expand-md bg-dark navbar-dark">

        <a class="navbar-brand" href="#">LinkedIn</a>


        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
            <span class="navbar-toggler-icon"></span>
        </button>


        <div class="collapse navbar-collapse" id="collapsibleNavbar">
            <ul class="navbar-nav">

                <li class="nav-item">
                    <a class="nav-link" href="{%url 'linkapps:index'%}">Home</a>
                </li>
                {%if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{%url 'linkapps:dashb'%}">Create Your Profile</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{%url 'linkapps:details1'%}">details</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{%url 'linkapps:logout'%}" style="margin-right: 300px;">Log Out</a>
                </li>
                <h2 style="color: aquamarine;">welcome!! {{user}}</h2>
                {%else%}



                <li class="nav-item">
                    <a class="nav-link" href="{%url 'linkapps:login'%}">Login</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{%url 'linkapps:register'%}">Register</a>
                </li>
                {%endif%}
            </ul>
        </div>
    </nav>
    <div class="row">
        <div class="col-lg-4 mx-auto shadow p-3 ml-3 mt-5">
            <form method="post" class="forms">
                {%csrf_token%}
                <table class="tables">
                    {%for i in form%}
                    <div class=" mt-2 "> {{i.label}}</div> {{i}}
                    {%endfor%}
                    <tr>
                        <td><input class="btn btn-success mt-3 " type="submit" value="Register"></td>
                        <td><input class="btn btn-success mt-3" type="reset" value="Reset"></td>
                    </tr>
                </table>
            </form>
        </div>
    </div>

 <br><br>
 <table border="1px" class="col-lg-4 mx-auto shadow p-3 ml-3 mt-5">
    <tr>
        <td>title</td>
        <td>date</td>
        <td>status</td>
        <td colspan="2">Action</td>
    </tr>

    {% for i in data %}
    <tr>
        <td>{{i.title}}</td>
        <td>{{i.date}}</td>
        <td>{{i.status}}</td>
        <td><a href="{% url 'linkapps:delete1' i.id%}">delete</a></td>
        <td><a href="{%url 'linkapps:edit1' i.id %}">edit</a></td>
    </tr>
    {% endfor %}

</table>

        




    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz"
        crossorigin="anonymous"></script>
</body>

</html>

linkapp/templates/forms.html
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
</head>

<body>

    <nav class="navbar navbar-expand-md bg-dark navbar-dark">

        <a class="navbar-brand" href="#">LinkedIn</a>


        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
            <span class="navbar-toggler-icon"></span>
        </button>


        <div class="collapse navbar-collapse" id="collapsibleNavbar">
            <ul class="navbar-nav">

                <li class="nav-item">
                    <a class="nav-link" href="{%url 'linkapps:index'%}">Home</a>
                </li>
                {%if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{%url 'linkapps:dashb'%}">Create Your Profile</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{%url 'linkapps:logout'%}" style="margin-right: 300px;">Log Out</a>
                </li>
                <h2 style="color: aquamarine;">welcome!! {{user}}</h2>
                {%else%}



                <li class="nav-item">
                    <a class="nav-link" href="{%url 'linkapps:login'%}">Login</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{%url 'linkapps:register'%}">Register</a>
                </li>
                {%endif%}
            </ul>
        </div>
    </nav>

    <div class="col-lg-5 shadow p-4 mx-auto mt-5">
        <form method="post" class="forms">
            {%csrf_token%}
            <table class="tables">
                {%for i in form%}
                <div class=" mt-2"> {{i.label}}</div> {{i}}
                {%endfor%}
                <tr>
                    <td><input class="btn btn-success mt-2 " type="submit" value="Register"></td>
                    <td><input class="btn btn-success mt-2" type="reset" value="Reset"></td>
                </tr>
            </table>
        </form>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz"
        crossorigin="anonymous"></script>
</body>

</html>

linkapp/templates/index.html
<!DOCTYPE html>
<html>

<head>
    {%load static%}
    <title>My E-commerce Site</title>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'css/mystyle.css' %}">
</head>

<body>
    <nav class="navbar navbar-expand-md bg-dark navbar-dark">

        <a class="navbar-brand" href="#">LinkedIn</a>


        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
            <span class="navbar-toggler-icon"></span>
        </button>


        <div class="collapse navbar-collapse" id="collapsibleNavbar">
            <ul class="navbar-nav">

                <li class="nav-item">
                    <a class="nav-link" href="{%url 'linkapps:index'%}">Home</a>
                </li>
                {%if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{%url 'linkapps:dashb'%}">Create Your Profile</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{%url 'linkapps:logout'%}" style="margin-right: 300px;">Log Out</a>
                </li>
                <h2 style="color: aquamarine;">welcome!! {{user}}</h2>
                {%else%}



                <li class="nav-item">
                    <a class="nav-link" href="{%url 'linkapps:login'%}">Login</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{%url 'linkapps:register'%}">Register</a>
                </li>
                {%endif%}
            </ul>
        </div>
    </nav>

    <div class="container">
        <div id="carouselExampleCaptions" class="carousel slide">
            <div class="carousel-indicators">
                <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active"
                    aria-current="true" aria-label="Slide 1"></button>
                <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1"
                    aria-label="Slide 2"></button>
                <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2"
                    aria-label="Slide 3"></button>
            </div>
            <div class="carousel-inner">
                <div class="carousel-item active">
                    <img src="{% static 'images/5.jpg' %}" class="d-block w-100" alt="...">
                    <div class="carousel-caption d-none d-md-block text-dark">
                        <h5>ToDo</h5>
                        <p>Start your every move with us.</p>
                    </div>
                </div>
                <div class="carousel-item">
                    <img src="{% static 'images/6.jpg' %}" class="d-block w-100" alt="...">
                    <div class="carousel-caption text-dark d-none d-md-block">
                        <h5>Schedule</h5>
                        <p>Make schedule for your target with our ToDo.</p>
                    </div>
                </div>
                <div class="carousel-item">
                    <img src="{% static 'images/7.jpg' %}" class="d-block w-100" alt="...">
                    <div class="carousel-caption text-dark d-none d-md-block">
                        <h5>Ready for Work</h5>
                        <p>Complete one by one target and get achievement.</p>
                    </div>
                </div>
            </div>
            <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions"
                data-bs-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Previous</span>
            </button>
            <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions"
                data-bs-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Next</span>
            </button>
        </div>
    </div>


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz"
        crossorigin="anonymous"></script>
</body>

linkapp/templates/sample.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <table border="1px" class="col-lg-4 mx-auto shadow p-3 ml-3 mt-5">
        <tr>
            <td>title</td>
            <td>date</td>
            <td>status</td>
            <td colspan="2">Action</td>
        </tr>

        {% for i in data %}
        <tr>
            <td>{{i.title}}</td>
            <td>{{i.date}}</td>
            <td>{{i.status}}</td>
            <td><a href="{% url 'linkapps:delete1' i.id%}">delete</a></td>
            <td><a href="{%url 'linkapps:edit1' i.id %}">edit</a></td>
        </tr>
        {% endfor %}

    </table>


</body>
</html>